<?php

#define("DB_DSN", "mysql:host=localhost;dbname=x25601566LOCAL");
define("DB_DSN", "mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/;dbname=appdeprueba");
define("DB_USUARIO", "adminWjH8lMV");
define("DB_CONTRASENIA", "HJfPeaHHVcL8");
define("TAMANIO_PAGINA", 5);
define("TABLA_USUARIOS", "usuario");
define("TABLA_NOTICIAS", "noticia");
define("TABLA_COMENTARIOS", "comentario");

?>
